name: CD - Deploy to dev

on:
  push:
    branches:
      - dev-i

permissions:
  contents: read
  id-token: write
  
jobs:
  deploy-qa:
    uses: ops-migration/github_shared_templates/.github/workflows/cd-workflow.yml@main
    with:
      cf-stack-name: "dev-stack"
