name: CI Pipeline

on:
  push:
    branches:
      - main
      - release/**
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  security-events: write
  id-token: write

jobs:
  ci:
    uses: ops-migration/github_shared_templates/.github/workflows/ci-workflow.yml@main
    with:
      ecr-repository: "dev-function-manager"
      aws-region: "us-east-1"
      target-branch: "dev-i"
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
